---
title: "Lab4"
author: "Kevin Zhai"
date: "11/27/2016"
output: pdf_document
---
1a.
```{r setup}
#State 10 after 10 transitions - at state 1
library(expm)
transition <- read.table('markov100.txt',header=F)
P <- as.matrix(transition)
a <- c(1,rep(0,99))
dist_a <- a %*% (P %^% 10)
print(dist_a[,5])
```
1b.
```{r}
#State 10 after 10 transitions - equal probabilites of 1,2,3
b <- c(rep(1/3,3),rep(0,97))
dist_b <- b %*% (P %^% 10)
print(dist_a[,10])
```
1c.
```{r}
#Steady State Probablity of State 1
Q <- t(P) - diag(100)
Q[100,] = c(rep(1,100))
rhs <- c(rep(0,99),1)
steady <- solve(Q) %*% rhs;
print(steady[1])
```
1d.
```{r}
#State 1 to 100 Mean Passage Time
B <- P[1:99,1:99]
Q_m <- diag(99) - B
e <- c(rep(1,99))
m <- solve(Q_m) %*% e
print(m[1])
```

2a.
```{r}
library(Matrix)
web <- read.table('webtraffic.txt',header=T)
traffic_temp <- colSums(web)
traffic <- as.matrix(traffic_temp)
dim(traffic) <- c(9,9)
traffic <- t(traffic)
print(traffic)
```

2b.
```{r}
traffic[9,1] <- 1000
P_traffic <- matrix(nrow=9,ncol=9)
for (i in seq(1,9,1)) {
  for (j in seq(1,9,1)){
    P_traffic[i,j] <- (traffic[i,j] / sum(traffic[i,]))
  }
}
print(P_traffic)
```

2c.
```{r}
Q_traffic <- t(P_traffic) - diag(9)
Q_traffic[9,] = c(rep(1,9))
rhs_2 <- c(rep(0,8),1)
steady_traffic <- solve(Q_traffic) %*% rhs_2
print(steady_traffic)
```

2d.
```{r}
averages <- c(0.1,2,3,5,5,3,3,2)
time <- c()
for (i in averages) {
  time <- append(time,averages[i] * steady_traffic[i])
}
print(sum(time))
```

2e.
```{r}
traffic_2 <- traffic
outgoing1 <- traffic[2,3] * 0.30
outgoing2 <- traffic[2,4] * 0.20
traffic_2[2,3] <- traffic[2,3] - outgoing1
traffic_2[2,4] <- traffic[2,4] - outgoing2
traffic_2[2,6] <- traffic[2,6] + outgoing1
traffic_2[2,7] <- traffic[2,7] + outgoing2

P_traffic2 <- matrix(nrow=9,ncol=9)
for (i in seq(1,9,1)) {
  for (j in seq(1,9,1)){
    P_traffic2[i,j] <- (traffic_2[i,j] / sum(traffic_2[i,]))
  }
}

Q_traffic2 <- t(P_traffic2) - diag(9)
Q_traffic2[9,] = c(rep(1,9))
rhs_3 <- c(rep(0,8),1)
steady_traffic2 <- solve(Q_traffic2) %*% rhs_3
print(steady_traffic2)
print(var(steady_traffic))
print(var(steady_traffic2))
```
The variance of the steady state for the first distribution is higher, since 0.0014 > 0.0012. Therefore, the new links helped the website traffic by lowering the variance. 
